<!DOCTYPE html>
<title>test</title>
<p>現在は<?= h(date('Y年m月d日H時i分s秒')) ?>です</p>
<ul><li><a href='/phpinfo.php'><code>phpinfo()</code></a></ul>
<hr>
<p><a href='https://github.com/zonuexe/oiraphp'>This code is licensed under AGPL.</a></p>

echo "<!DOCTYPE html>\n";
echo "<title>test</title>\n";
echo "<p>現在は" . h(date('Y年m月d日H時i分s秒')). "です</p>\n";
echo "<ul><li><a href='/phpinfo.php'><code>phpinfo()</code></a></ul>\n";
echo "<hr>\n";
echo "<p><a href='https://github.com/zonuexe/oiraphp'>This code is licensed under AGPL.</a></p>";
